version: '3.8'

services:
  app:
    container_name: app_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: app_db
      DB_PORT: 5432
      API_PORT: ${API_PORT}
      BCRYPT_SALTS: ${BCRYPT_SALTS}
      JWT_SECRET: ${JWT_SECRET}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - app_db
    networks:
      - app_network

  app_db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
